# .github/workflows/phpdoc.yml

name: Generate PHPDocumentor Documentation (Responsive)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks-out your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Sets up PHP and Composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      # 3. Install PHPDocumentor and the official RESPONSIVE template
      #    This is the modern, officially supported template.
      - name: Install Dependencies
        run: composer require --dev phpdocumentor/phpdocumentor phpdocumentor/template-responsive

      # 4. Runs PHPDocumentor using the responsive template
      - name: Generate API Documentation
        run: ./vendor/bin/phpdoc -d . -t docs/api --template="responsive" --ignore="vendor/*"

      # 5. Deploys the generated documentation to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/api
